-- Integration fixture generated by the actual Win32 Armament controls. This
-- crosses the environment transport boundary rather than repeating a C++
-- command expectation in a separate mock.
local env=dofile('mod/Scripts/environment.lua')
local path=assert(arg[1],'Supply the armament-environment.txt emitted by menu_window_test.exe')
local packet=assert(io.open(path,'r'))
local line=packet:read('*a');packet:close()
local id,command=env.parse(line)
assert(id and command=='FPVArmament 2 5.000000 1 0 30',line)
assert(line:match('^%d+ armament '),'External transport must use its lowercase allowlisted kind')
assert(not env.parse(line:gsub(' armament ',' FPVArmament ',1)),'Console commands are not environment transport kinds')

local rawOpen=io.open
local request=tostring(tonumber(id)-1)..' armament 0 1.000000 0 3\n'
local response,calls='',0
io.open=function(file,mode)
    if file=='fixture/environment.txt' and mode=='r' then
        return {read=function()return request end,close=function()end}
    end
    if file=='fixture/environment-response.txt' and mode=='w' then
        return {write=function(_,text)response=text;return true end,close=function()end}
    end
    return rawOpen(file,mode)
end
local poll=env.new('fixture/',function(actual)
    assert(actual==command,'The transport must forward the validated console command')
    calls=calls+1;return true,'armament_saved'
end,function()end)
request=line;poll(0);poll(.2)
assert(calls==1 and response==id..' sent armament_saved\n','The actual F6 packet must execute once and receive its matching response')
io.open=rawOpen
print('PASS actual Win32 Armament packet -> environment allowlist -> FPVArmament dispatch, matching response and no replay')
if arg[2]then
    packet=assert(rawOpen(arg[2],'r'));line=packet:read('*a');packet:close()
    id,command=env.parse(line)
    assert(id and command=='FPVArmament 3 1.750000 1 0 45',line)
    local settings=dofile('mod/Scripts/weapon_settings.lua')
    local parsed=assert(settings.parse(command:match('^FPVArmament (.+)$')))
    assert(settings.hasKamikaze(parsed.mode)and settings.hasGrenades(parsed.mode)and parsed.charges==0 and parsed.impactSpeed==45)
    request='';response='';calls=0
    io.open=function(file,mode)
        if file=='fixture/environment.txt'and mode=='r'then return {read=function()return request end,close=function()end}end
        if file=='fixture/environment-response.txt'and mode=='w'then return {write=function(_,text)response=text;return true end,close=function()end}end
        return rawOpen(file,mode)
    end
    poll=env.new('fixture/',function(actual)assert(actual==command);calls=calls+1;return true,'combined_saved'end,function()end)
    request=line;poll(0);poll(.2)
    assert(calls==1 and response==id..' sent combined_saved\n')
    io.open=rawOpen
    print('PASS actual Win32 combined-mode packet -> environment dispatch -> both weapon capabilities and no replay')
end
