local f=dofile('mod/Scripts/flight.lua')
local base=dofile('mod/Scripts/config.lua')
local input=dofile('mod/Scripts/input.lua')
local settings=dofile('mod/Scripts/pilot_settings.lua')
local function cfg(mode) return setmetatable({flight_mode=mode},{__index=base}) end
local neutral={roll=0,pitch=0,yaw=0,throttle=0.5}
local function run(s,u,c,seconds) for _=1,math.floor(seconds/c.step) do f.step(s,u,c,c.step) end end
local tilted=f.new({x=0,y=0,z=100},0);tilted.q=f.mul(f.axis(0,0,1,0.7),f.axis(1,0,0,0.6))
run(tilted,neutral,cfg('angle'),3)
assert(f.rotate(tilted.q,{x=0,y=0,z=1}).z>0.999,'Angle must level when sticks center')
local banked=f.new({x=0,y=0,z=100},0)
run(banked,{roll=1,pitch=0,yaw=0,throttle=0.5},cfg('angle'),3)
assert(math.abs(math.deg(math.acos(f.rotate(banked.q,{x=0,y=0,z=1}).z))-50)<1,'Angle bank limit')
local acro=f.new({x=0,y=0,z=100},0);acro.q=f.axis(1,0,0,0.6)
run(acro,neutral,cfg('acro'),1);assert(math.abs(acro.q.x-math.sin(0.3))<1e-6,'Acro must not auto-level')
local center=f.new({x=0,y=0,z=100},0);run(center,neutral,cfg('3d'),1)
assert(math.abs(center.thrust)<1e-9 and center.v.z<0,'3D center means zero thrust')
local upright=f.new({x=0,y=0,z=100},0);run(upright,{roll=0,pitch=0,yaw=0,throttle=1},cfg('3d'),1)
assert(upright.v.z>0 and upright.thrust>0,'3D positive thrust')
local inverted=f.new({x=0,y=0,z=100},0);inverted.q=f.axis(1,0,0,math.pi)
run(inverted,{roll=0,pitch=0,yaw=0,throttle=0},cfg('3d'),1)
assert(inverted.thrust<0 and inverted.v.z>0,'3D inverted flight requires reverse thrust')
assert(settings.valid_keys(117,119,120));assert(not settings.valid_keys(117,117,120));assert(not settings.valid_keys(0,119,120))
local p=input.parse('4 10 100000 1 1 1 2 3 4 5 6 7 8 0 0 3456 10')
assert(p and p.axes[8]==8 and p.device==3456 and not p.menu)
assert(not input.parse('4 10 100000 1 1 1 2 3 4 5 6 7 8 0 0 3456 11'))
print('PASS Angle leveling/bank, Acro preservation, 3D forward/center/reverse thrust, bindings, 8-axis packets')
