local guard=dofile('mod/Scripts/focus_guard.lua')
local g={}
local function packet(focused,menu,connected)
    return {focused=focused,menu=menu,connected=connected~=false,buttons=7}
end
local normal=packet(true,false)
assert(guard.accept(g,normal,0)==normal)
local away=packet(false,false)
local held=guard.accept(g,away,1)
assert(held and held.paused and not held.menu and not held.focused)
assert(not away.paused,'do not mutate the bridge sample')
assert(guard.accept(g,away,600).paused,'focus loss must preserve FPV indefinitely')
assert(not guard.accept(g,packet(false,false,false),601),'real disconnect must still exit')
local dt,paused=guard.delta(g,held,60)
assert(dt==0 and paused,'background physics must be held')
dt,paused=guard.delta(g,normal,60)
assert(dt==0 and not paused,'first resumed frame must discard the background interval')
assert(guard.delta(g,normal,.01)==.01)
local menu=packet(true,true)
assert(guard.accept(g,menu,602)==menu)
assert(guard.delta(g,menu,.01)==0,'F6 still holds physics')
assert(guard.delta(g,normal,2)==0,'menu resume discards elapsed time')
assert(guard.delta(g,normal,.01)==.01)
print('PASS focus loss holds FPV, discards background time, preserves menu state and exits on disconnect')
