#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <mmsystem.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <thread>
#include <vector>
#pragma comment(lib,"winmm.lib")

namespace fs=std::filesystem;
#include "drone_audio.h"
#include "language.h"
#include "osd.h"
#include "controllers.h"
#include "navigation_keys.h"
#include "action_bindings.h"
#include "action_exchange.h"
#include "controller_profiles.h"
#include "object_limit.h"
#include "weather_menu.h"
#include "pda_settings_bridge.h"
using Axes=std::array<DWORD,8>;
Axes axes(const JOYINFOEX& j){ return {j.dwXpos,j.dwYpos,j.dwZpos,j.dwRpos,j.dwUpos,j.dwVpos,controllers::extraAxes[0],controllers::extraAxes[1]}; }
bool read(UINT id,JOYINFOEX& j){j={};j.dwSize=sizeof(j);j.dwFlags=JOY_RETURNALL;return joyGetPosEx(id,&j)==JOYERR_NOERROR;}
struct Device {UINT id; JOYCAPSW caps;};
std::vector<Device> devices(){
    std::vector<Device> result;
    for(UINT id=0;id<joyGetNumDevs();++id){
        JOYCAPSW caps{};JOYINFOEX j{};
        if(joyGetDevCapsW(id,&caps,sizeof(caps))==JOYERR_NOERROR && read(id,j)) result.push_back({id,caps});
    }
    return result;
}
bool gameFocused(HWND foreground=GetForegroundWindow()){
    thread_local HWND cached=nullptr;thread_local bool result=false;
    thread_local ULONGLONG checked=0;const auto now=GetTickCount64();if(foreground==cached&&now-checked<1000)return result;cached=foreground;checked=now;
    // UE4SS GUI Console and other tools may share the game's PID. Only the
    // Unreal viewport is eligible for our hotkeys, input and overlay placement.
    wchar_t windowClass[128]{};
    if(!foreground||!IsWindowVisible(foreground)||IsIconic(foreground)||
       !GetClassNameW(foreground,windowClass,128)||wcscmp(windowClass,L"UnrealWindow")!=0){result=false;return false;}
    DWORD pid=0;GetWindowThreadProcessId(foreground,&pid);
    HANDLE p=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid);
    if(!p){result=false;return false;}
    wchar_t path[32768];DWORD size=32768;
    const bool found=QueryFullProcessImageNameW(p,0,path,&size)!=0;CloseHandle(p);
    result=found && _wcsicmp(fs::path(path).filename().c_str(),L"Stalker2-Win64-Shipping.exe")==0;return result;
}
int calibrate(UINT id,const fs::path& output){
    const char* names[]={"roll","pitch","throttle","yaw"};
    const char* directions[]={"RIGHT stick RIGHT","RIGHT stick FORWARD","LEFT stick UP (full throttle)","LEFT stick RIGHT"};
    std::ofstream file(output.string()+".tmp");
    if(!file)return 2;
    file<<"-- Generated by ZoneFPVInput. Raw WinMM axes are one-based.\nreturn {\n";
    std::array<bool,6> used{};
    for(int control=0;control<4;++control){
        std::cout<<"\n"<<names[control]<<": center both sticks (throttle LOW), press Enter.\n";
        std::string line;std::getline(std::cin,line);
        JOYINFOEX j{};if(!read(id,j))return 3;
        Axes center=axes(j),lo=center,hi=center,last=center;
        std::cout<<"For 6 seconds sweep ONLY this axis fully, then HOLD "<<directions[control]<<".\n";
        const auto start=GetTickCount64();
        while(GetTickCount64()-start<6000){
            if(!read(id,j))return 3;last=axes(j);
            for(int k=0;k<6;++k){lo[k]=std::min(lo[k],last[k]);hi[k]=std::max(hi[k],last[k]);}
            Sleep(8);
        }
        int best=0;for(int k=1;k<6;++k)if(hi[k]-lo[k]>hi[best]-lo[best])best=k;
        if(used[best]||hi[best]-lo[best]<10000){std::cerr<<"Ambiguous/no movement. Repeat calibration.\n";return 4;}
        const DWORD mid=lo[best]+(hi[best]-lo[best])/2;
        if(std::abs(static_cast<int>(last[best])-static_cast<int>(mid))<static_cast<int>((hi[best]-lo[best])/4)){
            std::cerr<<"Final direction not held. Repeat calibration.\n";return 4;
        }
        used[best]=true;
        file<<"  "<<names[control]<<"={axis="<<best+1<<",min="<<lo[best]<<",max="<<hi[best]
            <<",center="<<(control==2?mid:center[best])<<",invert="<<(last[best]<mid?"true":"false")<<"},\n";
        std::cout<<"Mapped axis "<<best+1<<".\n";
    }
    file<<"}\n";file.close();
    if(!MoveFileExW(fs::path(output.string()+".tmp").c_str(),output.c_str(),MOVEFILE_REPLACE_EXISTING))return 5;
    std::cout<<"Saved calibration.lua. Restart game to apply.\n";return 0;
}
int wmain(int argc,wchar_t** argv){
    wchar_t module[32768];GetModuleFileNameW(nullptr,module,32768);
    fs::path root=fs::path(module).parent_path();
    bool probe=false,cal=false,settings=false,limitSet=false,limitReset=false;int objectCount=0,selected=-1;unsigned seconds=0;DWORD parentPid=0;
    for(int i=1;i<argc;++i){
        std::wstring arg=argv[i];
        if(arg==L"--probe")probe=true;
        else if(arg==L"--settings")settings=true;
        else if(arg==L"--calibrate")cal=true;
        else if(arg==L"--device" && i+1<argc)selected=_wtoi(argv[++i]);
        else if(arg==L"--seconds" && i+1<argc)seconds=static_cast<unsigned>(_wtoi(argv[++i]));
        else if(arg==L"--parent-pid" && i+1<argc)parentPid=static_cast<DWORD>(_wtoi(argv[++i]));
        else if(arg==L"--output-dir" && i+1<argc)root=argv[++i];
        else if(arg==L"--object-limit" && i+1<argc){
            if(!objectLimit::parse(argv[++i],objectCount)){std::cerr<<"Object limit must be a positive 32-bit decimal integer.\n";return 1;}
            limitSet=true;
        }
        else if(arg==L"--object-limit-default")limitReset=true;
        else {std::cerr<<"Usage: ZoneFPVInput [--probe|--calibrate|--settings] [--device N] [--seconds N] [--parent-pid PID] [--output-dir PATH]\n"
            "Config: ZoneFPVInput --object-limit COUNT | --object-limit-default (restart game after change)\n";return 1;}
    }
    if(limitSet||limitReset){
        if(limitSet&&limitReset){std::cerr<<"Choose either a custom limit or reset to default.\n";return 1;}
        const auto path=objectLimit::defaultEnginePath();
        const auto result=limitReset?objectLimit::reset(path):objectLimit::set(path,objectCount);
        if(!result.ok){std::wcerr<<L"Engine.ini update failed: "<<result.error<<L"\n";return 2;}
        std::wcout<<(result.changed?L"Engine.ini updated. Restart game.\n":L"Engine.ini already matches.\n");
        if(!result.backupPath.empty())std::wcout<<L"Backup: "<<result.backupPath.c_str()<<L"\n";
        return 0;
    }
    // The normal helper discovers USB devices through DirectInput/XInput.
    // Repeated WinMM capability queries crashed the discovery worker in both
    // recorded failures. Keep the old single-purpose CLI path separate.
    const bool legacyCLI=cal||selected>=0;
    auto available=legacyCLI?devices():std::vector<Device>{};
    for(const auto& d:available){
        char name[256]{};WideCharToMultiByte(CP_UTF8,0,d.caps.szPname,-1,name,sizeof(name),nullptr,nullptr);
        std::cout<<"Joystick "<<d.id<<": "<<name<<"; axes="<<d.caps.wNumAxes<<" buttons="<<d.caps.wNumButtons<<"\n";
        JOYINFOEX j{};read(d.id,j);Sleep(100);read(d.id,j);for(auto a:axes(j))std::cout<<a<<" ";std::cout<<"buttons="<<j.dwButtons<<"\n";
    }
    controllers::scan(legacyCLI);
    if(probe){
        const auto start=GetTickCount64();
        const auto list=controllers::available;
        for(const auto& d:list){char name[512]{};WideCharToMultiByte(CP_UTF8,0,d.name.c_str(),-1,name,sizeof(name),nullptr,nullptr);JOYINFOEX j{};const bool ok=controllers::read(d.id,j);std::cout<<"Device "<<d.id<<": "<<name<<" backend="<<d.kind<<" connected="<<ok<<"\n";}
        std::cout<<"Read duration ms="<<GetTickCount64()-start<<"\n";controllers::cleanup();return 0;
    }
    if(available.empty()&&cal){std::cerr<<"No WinMM joystick for legacy CLI calibration. Use F6 for DirectInput / XInput.\n";return 2;}
    if(selected<0){

        if(!available.empty()&&(cal||fs::exists(root/L"calibration.lua")))selected=static_cast<int>(available.front().id);
    }
    if(selected>=0&&std::none_of(available.begin(),available.end(),[&](const Device& d){return d.id==static_cast<UINT>(selected);})){std::cerr<<"Device unavailable\n";return 2;}
    if(cal)return calibrate(static_cast<UINT>(selected),root/L"calibration.lua");
    auto instanceRoot=fs::absolute(root).lexically_normal().wstring();for(auto& c:instanceRoot)c=static_cast<wchar_t>(towlower(c));
    const auto instanceName=L"Local\\ZoneFPVInput-"+std::to_wstring(std::hash<std::wstring>{}(instanceRoot));
    HANDLE mutex=CreateMutexW(nullptr,TRUE,instanceName.c_str());
    if(!mutex||GetLastError()==ERROR_ALREADY_EXISTS){if(mutex)CloseHandle(mutex);return 6;}
    HANDLE parent=parentPid?OpenProcess(SYNCHRONIZE,FALSE,parentPid):nullptr;
    if(parentPid&&!parent){ReleaseMutex(mutex);CloseHandle(mutex);return 8;}
    unsigned device=selected>=0?static_cast<unsigned>(selected)+1:0;
    if(selected<0){std::ifstream f(root/L"controller.txt");unsigned saved=0;if(f>>saved)device=saved;}
    if(!device){std::lock_guard<std::mutex> lock(controllers::mutex);if(!controllers::available.empty())device=controllers::available.front().id;}
    controllers::requested=device;
    // Migrate the old radio calibration only once, never to a newly selected device.
    if(!fs::exists(root/L"controller-migrated.txt")&&device){
        const auto profile=root/("calibration-"+std::to_string(device)+".lua");
        std::error_code ec;if(device<100&&fs::exists(root/L"calibration.lua")&&!fs::exists(profile))fs::copy_file(root/L"calibration.lua",profile,ec);
        std::ofstream marker(root/L"controller-migrated.txt");marker<<device;
    }
    const auto snapshot=root/L"input.txt",temp=root/L"input.tmp";
    weatherMenu::root=root;osd::root=root;osd::load();
    {std::ifstream f(root/L"language.txt");int lang=0;if(f>>lang&&lang>=0&&lang<=4)language::current=lang;}
    {std::ifstream prefs(root/L"audio-volume.txt");float volume=0.5f;if(prefs>>volume && std::isfinite(volume) && volume>=0 && volume<=1)droneAudio::volume=volume;}
    // Wake the sole snapshot writer as soon as a menu begins opening/closing,
    // including when no controller is connected and discovery is idle.
    weatherMenu::modalChanged=CreateEventW(nullptr,FALSE,FALSE,nullptr);
    std::atomic<bool> menuStop{false};
    std::thread menuThread([&](){
        navigationKeys::State keys;bool publicationFailed=false;
        action_bindings::RuntimeActions actionKeys;
        actionExchange::Writer actionWriter;bool actionPublicationFailed=false;
        if(settings)weatherMenu::show();
        while(!menuStop){
            const auto foreground=GetForegroundWindow();
            const bool focus=gameFocused(foreground);
            const bool published=navigationKeys::publish(root,keys,focus&&!weatherMenu::visible(),(GetAsyncKeyState('Q')&0x8000)!=0,(GetAsyncKeyState('E')&0x8000)!=0);
            if(!published&&!publicationFailed)std::cerr<<"Cannot publish PDA keyboard state.\n";
            publicationFailed=!published;
            // Capture and runtime actions share a coherent input sample. UI
            // capture begins before runtime dispatch, so assigning a control
            // cannot execute its old action in the same update.
            const auto sample=weatherMenu::sampleSettingsHardware();
            pdaSettings::bridge.pump(root,sample,focus,GetTickCount64());
            weatherMenu::pump(focus,&sample,focus?foreground:nullptr);
            const auto bindings=weatherMenu::getCurrentBindings();
            const bool ownMenu=weatherMenu::focused();
            const bool menuVisible=weatherMenu::visible(),gameFocus=gameFocused();
            const bool menuInput=ownMenu||(menuVisible&&gameFocus);
            auto edges=actionKeys.poll(bindings,sample,gameFocus,menuInput,weatherMenu::capturing()||pdaSettings::bridge.blocking(),GetTickCount64());
            if(!weatherMenu::dispatchMenuState(edges[0],actionKeys.held()[0],bindings[0],menuInput,weatherMenu::currentModes().menu)&&edges[0])edges[0]=false;
            const bool actionsEligible=gameFocused()&&!weatherMenu::visible()&&!weatherMenu::capturing()&&!pdaSettings::bridge.blocking();
            const bool actionsPublished=actionWriter.publish(root,actionsEligible,edges,actionKeys.held());
            if(!actionsPublished&&!actionPublicationFailed)std::cerr<<"Cannot publish action input.\n";
            actionPublicationFailed=!actionsPublished;
            Sleep(osd::scanMarkers.empty()?16:8);
        }
        weatherMenu::cleanup();osd::cleanup();
    });
    std::thread audioThread([&](){droneAudio::run(root,menuStop);});
    std::cout<<"ZoneFPV input bridge running. Close this window / Ctrl+C to stop.\n";
    // Enumeration can block in a USB driver. Keep publishing input and servicing
    // the menu independently, so attaching a device cannot stall the bridge.
    // An explicit legacy device keeps its initial WinMM descriptor. Normal
    // rescans omit WinMM; running them here would silently switch backends.
    std::thread discoveryThread;
    if(!legacyCLI)discoveryThread=std::thread([&](){while(!menuStop){try{controllers::scan();}catch(const std::exception& e){std::cerr<<"Device scan: "<<e.what()<<"\n";}for(int i=0;i<20&&!menuStop;++i)Sleep(100);}});
    ULONGLONG seq=0,start=GetTickCount64();
    unsigned preparedDevice=0;
    timeBeginPeriod(1);
    unsigned errors=0;
    while(!seconds||GetTickCount64()-start<seconds*1000ULL){
        if(parent&&WaitForSingleObject(parent,0)!=WAIT_TIMEOUT)break;

        device=controllers::selectAvailable();
        controllers::active=device;
        JOYINFOEX j{};bool connected=device&&controllers::read(device,j);
        if(!device)controllers::publishLive({});
        if(!connected)preparedDevice=0;
        else if(device!=preparedDevice){try{controllerProfiles::ensure(root,device);preparedDevice=device;}catch(const std::exception& e){std::cerr<<"Profile: "<<e.what()<<"\n";}}
        auto raw=axes(j);
        weatherMenu::joystickConnected=connected;
        for(int i=0;i<8;++i)weatherMenu::liveAxes[i]=connected?raw[i]:0;
        const auto epoch=std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
        char line[512];
        ++seq;
        const bool menu=weatherMenu::visible();
        int count=snprintf(line,sizeof(line),"4 %llu %lld %d %d %lu %lu %lu %lu %lu %lu %lu %lu %lu %d %u %llu\n",seq,epoch,
            connected?1:0,(gameFocused()||weatherMenu::focused())?1:0,raw[0],raw[1],raw[2],raw[3],raw[4],raw[5],raw[6],raw[7],j.dwButtons,menu?1:0,device,seq);
        // Replacing a closed temporary file keeps readers from observing a torn packet.
        HANDLE f=CreateFileW(temp.c_str(),GENERIC_WRITE,FILE_SHARE_READ,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_TEMPORARY,nullptr);
        DWORD written=0;bool ok=f!=INVALID_HANDLE_VALUE;
        if(ok){ok=WriteFile(f,line,static_cast<DWORD>(count),&written,nullptr)&&written==static_cast<DWORD>(count);CloseHandle(f);}
        if(ok)ok=MoveFileExW(temp.c_str(),snapshot.c_str(),MOVEFILE_REPLACE_EXISTING)!=0;
        if(!ok && ++errors>=250){std::cerr<<"Cannot publish input snapshot.\n";break;}
        if(ok)errors=0;
        const DWORD interval=connected||menu?8:100;
        if(weatherMenu::modalChanged)WaitForSingleObject(weatherMenu::modalChanged,interval);else Sleep(interval);
    }
    menuStop=true;if(weatherMenu::window)PostMessageW(weatherMenu::window,WM_CANCELMODE,0,0);
    if(discoveryThread.joinable())discoveryThread.join();
    menuThread.join();
    audioThread.join();
    if(weatherMenu::modalChanged){CloseHandle(weatherMenu::modalChanged);weatherMenu::modalChanged=nullptr;}
    controllers::cleanup();timeEndPeriod(1);if(parent)CloseHandle(parent);ReleaseMutex(mutex);CloseHandle(mutex);return errors?7:0;
}
